In [ ]:
## Download Data From Kaggle 

## url = "https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"

In [136]:
import pandas as pd
import numpy as np

In [137]:
imdb = pd.read_csv("IMDB Dataset.csv")

In [138]:
imdb.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [139]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
review       50000 non-null object
sentiment    50000 non-null object
dtypes: object(2)
memory usage: 781.4+ KB


In [140]:
imdb.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  negative
freq                                                    5     25000

In [141]:
def sentiment(data):
    if data=="positive":
        data = 1
    else:
        data=0
    return data

In [142]:
imdb["sentiment"] = imdb["sentiment"].apply(sentiment)

In [143]:
imdb.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [144]:
imdb.dtypes

review       object
sentiment     int64
dtype: object

In [145]:
imdb["sentiment"].mean()

0.5

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
X_train,X_test,y_train,y_test = train_test_split(imdb["review"],imdb["sentiment"],random_state=0)

In [148]:
X_train.iloc[0]

"This is a story of two dogs and a cat looking for their way back home.Old and wise Golden Retriever Shadow, young American Bulldog Chance and Himalayan cat Sassy flee from the ranch and go into the wilderness to be reunited with their family.Homeward Bound: The Incredible Journey (1993) is a family adventure directed by Duwayne Dunham.It's a remake of a 1963 film.This movie got a sequel three years later.Michael J. Fox is the perfect man to do the voice-over for Chance.Fox has some youthful energy he brings to the role.Sally Field does great voice work as Sassy.Don Ameche is fantastic as Shadow.This was this veteran actor's second last movie.Also the visible actors are great.Kim Greist plays Laura Burnford-Seaver.Robert Hays is Bob Seaver.Benji Thall plays Peter Burnford.Veronica Lauren is Hope Burnford.Kevin Chevalia is Jamie Seaver.Jean Smart portrays Kate.It's quite amazing to watch these pets trying to survive in the wilderness.We see Sassy taken by the river and she seems like a 

In [149]:
y_train.iloc[0]

1

In [150]:
from sklearn.feature_extraction.text import CountVectorizer

In [151]:
vect = CountVectorizer().fit(X_train)

In [152]:
vect.get_feature_names()[::2000]

['00',
 'actionless',
 'andlaurel',
 'audiobooks',
 'befits',
 'bolo',
 'bushwhackers',
 'chalie',
 'cochlear',
 'cornered',
 'danube',
 'diabolik',
 'dozing',
 'emile',
 'expressively',
 'flashiness',
 'gake',
 'goths',
 'hark',
 'hoodwinks',
 'indecent',
 'janaya',
 'kidnappers',
 'leaches',
 'luján',
 'mathematically',
 'mirages',
 'myabe',
 'nunn',
 'oxbow',
 'petulant',
 'powerhouses',
 'quartmaster',
 'rejenacyn',
 'romania',
 'schfrin',
 'shin',
 'snippers',
 'static',
 'surmising',
 'teuton',
 'transvestive',
 'unended',
 'via',
 'whisk',
 'zakk']

In [153]:
len(vect.get_feature_names())

90506

In [154]:
X_train_vect = vect.transform(X_train)

In [155]:
X_train_vect

<37500x90506 sparse matrix of type '<class 'numpy.int64'>'
	with 5111856 stored elements in Compressed Sparse Row format>

In [156]:
from sklearn.linear_model import LogisticRegression

In [157]:
model = LogisticRegression(max_iter=400)
model.fit(X_train_vect,y_train)

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [158]:
y_pred = model.predict(vect.transform(X_test))

In [159]:
from sklearn.metrics import roc_auc_score,accuracy_score,confusion_matrix

In [160]:
accuracy_score(y_test,y_pred)

0.88408

In [161]:
roc_auc_score(y_test,y_pred)

0.884116472314623

In [162]:
confusion_matrix(y_test,y_pred)

array([[5527,  764],
       [ 685, 5524]], dtype=int64)

In [176]:
feature_names = np.array(vect.get_feature_names())
sorted_coef_index = model.coef_[0].argsort()

print("Smallest Coefs : \n {}".format(feature_names[sorted_coef_index[:10]]))
print("Largest Coefs: \n{}".format(feature_names[sorted_coef_index[:-11:-1]]))

Smallest Coefs : 
 ['worst' 'waste' 'forgettable' 'awful' 'disappointing' 'disappointment'
 'stinker' 'poorly' 'fails' 'uninteresting']
Largest Coefs: 
['refreshing' 'hooked' 'wonderfully' 'raunchy' 'adr' 'superb' 'perfect'
 'delightful' 'squirrel' 'funniest']


In [182]:
word = ["this movie is funny"]

In [183]:
model.predict(vect.transform(word))

array([1], dtype=int64)

In [197]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [198]:
vect = TfidfVectorizer(min_df=5)
vect.fit(X_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=5, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [199]:
len(vect.get_feature_names())

32673

In [200]:
X_train_vect = vect.transform(X_train)

In [201]:
model = LogisticRegression(max_iter=400)
model.fit(X_train_vect,y_train)

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [202]:
y_pred = model.predict(vect.transform(X_test))

In [203]:
accuracy_score(y_test,y_pred)

0.89328

In [204]:
roc_auc_score(y_test,y_pred)

0.8933488824184665

In [205]:
confusion_matrix(y_test,y_pred)

array([[5554,  737],
       [ 597, 5612]], dtype=int64)

In [206]:
vect = CountVectorizer(min_df=5,ngram_range=(1,2))
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=5,
                ngram_range=(1, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [207]:
X_train_vect = vect.transform(X_train)

In [208]:
len(vect.get_feature_names())

213759

In [209]:
model = LogisticRegression(max_iter=400)
model.fit(X_train_vect,y_train)

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=400,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [214]:
y_pred = model.predict(vect.transform(X_test))

In [215]:
accuracy_score(y_test,y_pred)

0.904

In [216]:
roc_auc_score(y_test,y_pred)

0.9040357551130712

In [217]:
confusion_matrix(y_test,y_pred)

array([[5653,  638],
       [ 562, 5647]], dtype=int64)

In [219]:
feature_names = np.array(vect.get_feature_names())

sorted_coef_index = model.coef_[0].argsort()

print("Smallest Coefs : \n {}".format(feature_names[sorted_coef_index[:10]]))
print("Largest Coefs: \n{}".format(feature_names[sorted_coef_index[:-11:-1]]))

Smallest Coefs : 
 ['worst' 'awful' 'boring' 'waste' 'disappointment' 'terrible'
 'disappointing' 'horrible' 'not worth' 'poorly']
Largest Coefs: 
['perfect' 'excellent' 'hilarious' 'gem' 'amazing' 'superb' 'loved this'
 'today' 'incredible' 'well worth']


In [233]:
from sklearn.model_selection import cross_val_score

In [235]:
score = cross_val_score(LogisticRegression(max_iter=400),X_train_vect,y_train,cv=5)
print("Mean cv accuracy: {:.2f}".format(np.mean(score)))

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Mean cv accuracy: 0.90


In [236]:
from sklearn.model_selection import GridSearchCV

In [237]:
param_grid = {"C":[0.001,0.01,0.1,1,10]}
grid = GridSearchCV(LogisticRegression(max_iter=400),param_grid=param_grid)

grid.fit(X_train_vect,y_train)


print("Best CV Score : {:.3f}".format(grid.best_score_))
print("Best parameters : ",grid.best_params_)

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Best CV Score : 0.910
Best parameters :  {'C': 10}


In [252]:
from sklearn.pipeline import make_pipeline

In [254]:

pipe = make_pipeline(TfidfVectorizer(min_df=5),LogisticRegression(max_iter=400))

param_grid = {"logisticregression__C":[0.001,0.01,0.1,10,100]}
grid = GridSearchCV(pipe,param_grid,cv=5)
grid.fit(X_train,y_train)

print("Best CV Score : {:.3f}".format(grid.best_score_))
print("Best parameter : ",grid.best_params_)

C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\raada\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

Best CV Score : 0.890
Best parameter :  {'logisticregression__C': 0.1}
